#!/usr/bin/env python3

#
# This file is part of mquickjs on LiteX.
#
# Copyright (c) 2026 EnjoyDigital <florent@enjoy-digital.fr>
# SPDX-License-Identifier: BSD-2-Clause

import sys
from pathlib import Path


# Main ---------------------------------------------------------------------------------------------

def main():
    if len(sys.argv) != 3:
        print("usage: embed_script.py <input>.js <output>.h", file=sys.stderr)
        sys.exit(2)

    src  = Path(sys.argv[1])
    dst  = Path(sys.argv[2])
    data = src.read_bytes()

    dst.parent.mkdir(parents=True, exist_ok=True)

    # mquickjs's parser does one-byte lookahead past `src_len`, so we
    # terminate the blob with a trailing 0x00 that the parser will see
    # as end-of-input rather than reading a random .rodata byte. The
    # reported `user_script_len` stays at the original file length;
    # the terminator is extra.
    payload = data + b"\x00"

    lines = [
        "// Auto-generated by tools/embed_script.py - do not edit.",
        f"// source: {src.name} ({len(data)} bytes + 1 NUL sentinel)",
        "#ifndef LITEX_MQJS_USER_SCRIPT_H",
        "#define LITEX_MQJS_USER_SCRIPT_H",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "static const uint8_t user_script[] = {",
    ]
    for i in range(0, len(payload), 12):
        chunk = payload[i:i + 12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines += [
        "};",
        f"static const size_t user_script_len = {len(data)};",
        "#endif",
        "",
    ]
    dst.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
