#!/usr/bin/env python3

#
# This file is part of mquickjs on LiteX.
#
# Copyright (c) 2026 EnjoyDigital <florent@enjoy-digital.fr>
# SPDX-License-Identifier: BSD-2-Clause

import sys
from pathlib import Path


# Main ---------------------------------------------------------------------------------------------

def main():
    if len(sys.argv) != 4:
        print("usage: embed_asset.py <input> <output>.h <symbol>", file=sys.stderr)
        sys.exit(2)

    src    = Path(sys.argv[1])
    dst    = Path(sys.argv[2])
    symbol = sys.argv[3]
    data   = src.read_bytes()

    dst.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "// Auto-generated by firmware/embed_asset.py - do not edit.",
        f"// source: {src.name} ({len(data)} bytes + 1 NUL sentinel)",
        "#include <stddef.h>",
        "#include <stdint.h>",
        f"static const char {symbol}[] = {{",
    ]
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines += [
        "    0x00,",
        "};",
        f"static const size_t {symbol}_len = {len(data)};",
        "",
    ]
    dst.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
