// Copyright (c) 2026 EnjoyDigital <florent@enjoy-digital.fr>
// SPDX-License-Identifier: BSD-2-Clause
//
// Entry point for the LiteX-mquickjs firmware.
//
// Two execution modes are selected at compile time:
//   - MQJS_SCRIPT_EMBEDDED: `user_script.h` provides `user_script[]` and
//     `user_script_len`. The firmware evaluates it once at boot and prints
//     a completion marker that the test harness scrapes from the UART.
//   - otherwise: a minimal line-based REPL over UART, terminated by the
//     literal string `.exit` on its own line.

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include <irq.h>
#include <libbase/console.h>
#include <libbase/uart.h>
#include <generated/csr.h>

#include "mquickjs.h"
#include "mqjs_port.h"
#include "mqjs_config.h"

/* Generated by the host-side mqjs_stdlib_litex tool; defines `js_stdlib`
 * and the atom table referenced by mquickjs.c. */
#include "mqjs_stdlib.h"

#if defined(MQJS_SCRIPT_EMBEDDED)
#  include "user_script.h"
#endif

/* -------------------------------------------------------------------- */
/* JS heap                                                              */
/* -------------------------------------------------------------------- */

/* mquickjs allocates all JS objects inside this buffer; it never calls
 * the C malloc(). Sized by mqjs_config.h (default 1 MiB). */
static uint8_t mqjs_heap[LITEX_MQJS_HEAP_SIZE] __attribute__((aligned(16)));

/* -------------------------------------------------------------------- */
/* Error printing                                                       */
/* -------------------------------------------------------------------- */

static void dump_exception(JSContext *ctx)
{
    JSValue e = JS_GetException(ctx);
    fputs("error: ", stdout);
    JS_PrintValueF(ctx, e, JS_DUMP_LONG);
    putchar('\n');
}

static int run_source(JSContext *ctx, const char *src, size_t src_len,
                      const char *filename, int eval_flags)
{
    JSValue val = JS_Eval(ctx, src, src_len, filename, eval_flags);
    if (JS_IsException(val)) {
        dump_exception(ctx);
        return -1;
    }
    return 0;
}

/* -------------------------------------------------------------------- */
/* Interactive REPL                                                     */
/* -------------------------------------------------------------------- */

#if !defined(MQJS_SCRIPT_EMBEDDED)

static char line_buf[LITEX_MQJS_LINE_MAX];

static int read_line(void)
{
    int len = 0;
    while (len < (int)sizeof(line_buf) - 1) {
        char c = getchar();
        if (c == '\r' || c == '\n') {
            putchar('\n');
            line_buf[len] = 0;
            return len;
        } else if (c == 0x7f || c == 0x08) {
            if (len > 0) {
                len--;
                fputs("\b \b", stdout);
            }
        } else if (c >= 0x20 && c < 0x7f) {
            line_buf[len++] = c;
            putchar(c);
        }
    }
    line_buf[len] = 0;
    return len;
}

static void repl(JSContext *ctx)
{
    puts("mqjs REPL. Type .exit to quit, .gc to run GC.\n");
    for (;;) {
        fputs("> ", stdout);
        int len = read_line();
        if (len == 0)
            continue;
        if (strcmp(line_buf, ".exit") == 0)
            return;
        if (strcmp(line_buf, ".gc") == 0) {
            JS_GC(ctx);
            puts("gc ok");
            continue;
        }
        run_source(ctx, line_buf, (size_t)len, "<stdin>",
                   JS_EVAL_RETVAL | JS_EVAL_REPL);
    }
}

#endif /* !MQJS_SCRIPT_EMBEDDED */

/* -------------------------------------------------------------------- */
/* Main                                                                 */
/* -------------------------------------------------------------------- */

int main(void)
{
#ifdef CONFIG_CPU_HAS_INTERRUPT
    irq_setmask(0);
    irq_setie(1);
#endif
    uart_init();

    puts("\n--========= litex_mquickjs =========--");
    printf("mquickjs heap:   %u bytes\n", (unsigned)sizeof(mqjs_heap));
    printf("CPU:             %s @ %u Hz\n",
           CONFIG_CPU_HUMAN_NAME, (unsigned)CONFIG_CLOCK_FREQUENCY);

    JSContext *ctx = JS_NewContext(mqjs_heap, sizeof(mqjs_heap), &js_stdlib);
    if (!ctx) {
        puts(LITEX_MQJS_FAIL_MARKER ": JS_NewContext failed");
        while (1) { }
    }
    JS_SetLogFunc(ctx, mqjs_log_func);

#if defined(MQJS_SCRIPT_EMBEDDED)
    int rc;
    if (JS_IsBytecode(user_script, user_script_len)) {
        puts("running embedded bytecode...");
        if (JS_RelocateBytecode(ctx, (uint8_t *)user_script, user_script_len)) {
            puts(LITEX_MQJS_FAIL_MARKER ": bytecode relocation failed");
            while (1) { }
        }
        JSValue val = JS_LoadBytecode(ctx, user_script);
        if (JS_IsException(val)) {
            dump_exception(ctx);
            puts(LITEX_MQJS_FAIL_MARKER);
            while (1) { }
        }
        val = JS_Run(ctx, val);
        rc = JS_IsException(val) ? -1 : 0;
        if (rc != 0)
            dump_exception(ctx);
    } else {
        puts("running embedded script...");
        rc = run_source(ctx, (const char *)user_script, user_script_len,
                        "user_script.js", 0);
    }
    /* Run GC before dumping so the numbers reflect live state rather
     * than the watermark at program exit. */
    JS_GC(ctx);
    fputs("mqjs memory: ", stdout);
    JS_DumpMemory(ctx, 0);
    puts(rc == 0 ? LITEX_MQJS_DONE_MARKER : LITEX_MQJS_FAIL_MARKER);
#else
    repl(ctx);
    puts(LITEX_MQJS_DONE_MARKER);
#endif

    /* Halt — the simulator watches for the DONE/FAIL marker above and
     * shuts down the run. */
    for (;;) { }
    return 0;
}
