// Copyright (c) 2026 EnjoyDigital <florent@enjoy-digital.fr>
// SPDX-License-Identifier: BSD-2-Clause
//
// Entry point for the LiteX-mquickjs firmware.
//
// Two execution modes are selected at compile time:
//   - MQJS_SCRIPT_EMBEDDED: `user_script.h` provides `user_script[]` and
//     `user_script_len`. The firmware evaluates it once at boot and prints
//     a completion marker that the test harness scrapes from the UART.
//   - otherwise: a minimal line-based REPL over UART, terminated by the
//     literal string `.exit` on its own line.

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include <irq.h>
#include <libbase/console.h>
#include <libbase/uart.h>
#include <generated/csr.h>
#include <generated/soc.h>

#if LITEX_MQJS_LIVE_UDP
#include <libliteeth/udp.h>
#endif

#include "mquickjs.h"
#include "mqjs_port.h"
#include "mqjs_config.h"
#include "live_runtime.h"

#if LITEX_MQJS_LIVE_HTTP
#include "live_http.h"
#endif

/* Generated by the host-side mqjs_stdlib_litex tool; defines `js_stdlib`
 * and the atom table referenced by mquickjs.c. */
#include "mqjs_stdlib.h"

#if defined(MQJS_SCRIPT_EMBEDDED)
#  include "user_script.h"
#endif

/* -------------------------------------------------------------------- */
/* JS heap                                                              */
/* -------------------------------------------------------------------- */

/* mquickjs allocates all JS objects inside this buffer; it never calls
 * the C malloc(). Sized by mqjs_config.h (default 1 MiB). */
static uint8_t mqjs_heap[LITEX_MQJS_HEAP_SIZE] __attribute__((aligned(16)));

JSContext *new_mqjs_context(void)
{
    return new_mqjs_context_with_heap(mqjs_heap, sizeof(mqjs_heap));
}

JSContext *new_mqjs_context_with_heap(void *heap, size_t heap_size)
{
    JSContext *ctx = JS_NewContext(heap, heap_size, &js_stdlib);

    if (ctx)
        JS_SetLogFunc(ctx, mqjs_log_func);
    return ctx;
}

/* -------------------------------------------------------------------- */
/* Error printing                                                       */
/* -------------------------------------------------------------------- */

static void dump_exception(JSContext *ctx)
{
    JSValue e = JS_GetException(ctx);
    fputs("error: ", stdout);
    JS_PrintValueF(ctx, e, JS_DUMP_LONG);
    putchar('\n');
}

int run_source(JSContext *ctx, const char *src, size_t src_len,
               const char *filename, int eval_flags)
{
    JSValue val = JS_Eval(ctx, src, src_len, filename, eval_flags);
    if (JS_IsException(val)) {
        dump_exception(ctx);
        return -1;
    }
    return 0;
}

/* -------------------------------------------------------------------- */
/* Interactive REPL                                                     */
/* -------------------------------------------------------------------- */

#if !defined(MQJS_SCRIPT_EMBEDDED)

static char line_buf[LITEX_MQJS_LINE_MAX];

static int read_line(void)
{
    int len = 0;
    while (len < (int)sizeof(line_buf) - 1) {
        char c = getchar();
        if (c == '\r' || c == '\n') {
            putchar('\n');
            line_buf[len] = 0;
            return len;
        } else if (c == 0x7f || c == 0x08) {
            if (len > 0) {
                len--;
                fputs("\b \b", stdout);
            }
        } else if (c >= 0x20 && c < 0x7f) {
            line_buf[len++] = c;
            putchar(c);
        }
    }
    line_buf[len] = 0;
    return len;
}

static void repl(JSContext *ctx)
{
    puts("mqjs REPL. Type .exit to quit, .gc to run GC.\n");
    for (;;) {
        fputs("> ", stdout);
        int len = read_line();
        if (len == 0)
            continue;
        if (strcmp(line_buf, ".exit") == 0)
            return;
        if (strcmp(line_buf, ".gc") == 0) {
            JS_GC(ctx);
            puts("gc ok");
            continue;
        }
        run_source(ctx, line_buf, (size_t)len, "<stdin>",
                   JS_EVAL_RETVAL | JS_EVAL_REPL);
    }
}

#endif /* !MQJS_SCRIPT_EMBEDDED */

/* -------------------------------------------------------------------- */
/* Live JavaScript loader                                               */
/* -------------------------------------------------------------------- */

#if LITEX_MQJS_LIVE_DEMO

#if LITEX_MQJS_LIVE_HTTP

#if defined(CSR_ETHMAC_BASE)

static void live_loop(JSContext **ctxp)
{
    live_http_loop(ctxp);
}

#else

static void live_loop(JSContext **ctxp)
{
    (void)ctxp;
    puts("[live] Ethernet support is not present in this SoC");
}

#endif

#elif LITEX_MQJS_LIVE_UDP

#ifndef LITEX_MQJS_LIVE_PORT
#define LITEX_MQJS_LIVE_PORT 12345
#endif

#if defined(CSR_ETHMAC_BASE)

#ifdef MACADDR1
static const uint8_t live_mac[6] = {MACADDR1, MACADDR2, MACADDR3,
                                    MACADDR4, MACADDR5, MACADDR6};
#else
static const uint8_t live_mac[6] = {0x10, 0xe2, 0xd5, 0x00, 0x00, 0x00};
#endif

#ifdef LOCALIP1
static const unsigned int live_ip[4] = {LOCALIP1, LOCALIP2, LOCALIP3, LOCALIP4};
#else
static const unsigned int live_ip[4] = {192, 168, 1, 50};
#endif

static char live_script[8192];
static volatile uint32_t live_script_len;
static volatile uint8_t live_pending;
static uint32_t live_src_ip;
static uint16_t live_src_port;

static void live_udp_rx(uint32_t src_ip, uint16_t src_port, uint16_t dst_port,
                        void *data, uint32_t length)
{
    if (dst_port != LITEX_MQJS_LIVE_PORT)
        return;
    if (length >= sizeof(live_script))
        length = sizeof(live_script) - 1;

    memcpy(live_script, data, length);
    live_script[length] = 0;
    live_script_len = length;
    live_src_ip = src_ip;
    live_src_port = src_port;
    live_pending = 1;
}

static void live_send_reply(uint32_t dst_ip, uint16_t dst_port, const char *text)
{
    size_t len = strlen(text);
    char *tx;

    if (len > UDP_BUFSIZE)
        len = UDP_BUFSIZE;
    if (!udp_arp_resolve(dst_ip))
        return;
    tx = udp_get_tx_buffer();
    memcpy(tx, text, len);
    udp_send(LITEX_MQJS_LIVE_PORT, dst_port, len);
}

static void live_loop(JSContext **ctxp)
{
    puts("[live] starting Ethernet JavaScript receiver");
    printf("[live] local IP: %u.%u.%u.%u\n",
           live_ip[0], live_ip[1], live_ip[2], live_ip[3]);
    printf("[live] UDP port: %u\n", LITEX_MQJS_LIVE_PORT);
    puts("[live] run: ./tools/live_bridge.py --board 192.168.1.50");

    eth_init();
    udp_start(live_mac, IPTOINT(live_ip[0], live_ip[1], live_ip[2], live_ip[3]));
    udp_set_callback(live_udp_rx);

    for (;;) {
        udp_service();
        if (!live_pending)
            continue;

        live_pending = 0;
        printf("[live] received %u bytes from %u.%u.%u.%u:%u\n",
               (unsigned)live_script_len,
               (unsigned)((live_src_ip >> 24) & 0xff),
               (unsigned)((live_src_ip >> 16) & 0xff),
               (unsigned)((live_src_ip >>  8) & 0xff),
               (unsigned)((live_src_ip >>  0) & 0xff),
               live_src_port);

        JS_FreeContext(*ctxp);
        *ctxp = new_mqjs_context();
        if (*ctxp == NULL) {
            puts("[live] JS_NewContext failed");
            live_send_reply(live_src_ip, live_src_port, "ERR JS_NewContext failed\n");
            continue;
        }

        if (run_source(*ctxp, live_script, live_script_len,
                       "live_udp.js", JS_EVAL_REPL) == 0) {
            puts("[live] script ok");
            live_send_reply(live_src_ip, live_src_port, "OK\n");
        } else {
            puts("[live] script failed");
            live_send_reply(live_src_ip, live_src_port, "ERR script failed\n");
        }
    }
}

#else

static void live_loop(JSContext **ctxp)
{
    (void)ctxp;
    puts("[live] Ethernet support is not present in this SoC");
}

#endif

#endif /* LITEX_MQJS_LIVE_HTTP/LITEX_MQJS_LIVE_UDP */

#endif /* LITEX_MQJS_LIVE_DEMO */

/* -------------------------------------------------------------------- */
/* Main                                                                 */
/* -------------------------------------------------------------------- */

int main(void)
{
#ifdef CONFIG_CPU_HAS_INTERRUPT
    irq_setmask(0);
    irq_setie(1);
#endif
    uart_init();

    puts("\n"
         "   __  _______       _     __      ______              __   _ __      _  __\n"
         "  /  |/  / __ \\__ __(_)___/ /____ / / __/ ___  ___    / /  (_) /____ | |/_/\n"
         " / /|_/ / /_/ / // / / __/  '_/ // /\\ \\  / _ \\/ _ \\  / /__/ / __/ -_)>  <\n"
         "/_/  /_/\\___\\_\\_,_/_/\\__/_/\\_\\\\___/___/  \\___/_//_/ /____/_/\\__/\\__/_/|_|\n");
    puts("--========= mquickjs on LiteX =========--");
    printf("mquickjs heap:   %u bytes\n", (unsigned)sizeof(mqjs_heap));
    printf("CPU:             %s @ %u Hz\n",
           CONFIG_CPU_HUMAN_NAME, (unsigned)CONFIG_CLOCK_FREQUENCY);

    JSContext *ctx = new_mqjs_context();
    if (!ctx) {
        puts(LITEX_MQJS_FAIL_MARKER ": JS_NewContext failed");
        while (1) { }
    }

#if defined(MQJS_SCRIPT_EMBEDDED)
    puts("running embedded script...");
    int rc = run_source(ctx, (const char *)user_script, user_script_len,
                        "user_script.js", JS_EVAL_REPL);
#if LITEX_MQJS_DUMP_MEMORY
    /* Run GC before dumping so the numbers reflect live state rather
     * than the watermark at program exit. */
    JS_GC(ctx);
    fputs("mqjs memory: ", stdout);
    JS_DumpMemory(ctx, 0);
#endif
    puts(rc == 0 ? LITEX_MQJS_DONE_MARKER : LITEX_MQJS_FAIL_MARKER);
#if LITEX_MQJS_LIVE_DEMO
    if (rc == 0)
        live_loop(&ctx);
#endif
#else
    repl(ctx);
    puts(LITEX_MQJS_DONE_MARKER);
#endif

    /* Halt — the simulator watches for the DONE/FAIL marker above and
     * shuts down the run. */
    for (;;) { }
    return 0;
}
